/*
Maze Game : Develpment Edition 0.01
Written By: Brandon Clark

class file: Game.cpp

Information: This class is used to generate new levels and the
conditions around incremented levels difficulty.  It also 
destroys the dynamic pointer generated by Maze.h. 

CSUF Info:  

Development Notes:
In progress.
*/
#include "Game.h"
#include "Maze.h"

Game::Game(void)
{	
}

Game::Game(int w,int h) : Maze(iIncrement(w),iIncrement(h))
{	
	lvl = 0;
}

Game::~Game(void)
{
}

float	iValue		(float)
{
	return 0;
}

int		iValue		(int)
{
	return 0;
}

void	start		(void)
{
		// Default values for new game.
}

void	setLvl		(int)
{
}

float	iIncrement	(float i)
{
	i++;
	return i;
}

int		iIncrement	(int i)
{
	i++;
	return i;
}

float	iDecrement	(float i)
{
	i--;
	return i;
}

int	iDecrement	(int i)
{
	i--;
	return i;
}

void	end			(void)
{
}

void	testPrint	(void) 
{
	Maze:testPrint();
}